language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  global:
    - PLUGIN_NAME=Theme
    - REQUIRE=""
    - DB=sqlite
    - CAKE_REF=2.8.9

matrix:
  include:
    - php: 5.3
      env:
        - CAKE_REF=2.6.12
    - php: 5.3 
      env:
        - CAKE_REF=2.7.11
    - php: 5.3 
      env:
        - CAKE_REF=2.8.9
    - php: 5.6
      env:
        - PHPCS=1

before_script:
  - git clone -b master https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - travis_wait ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
